// File generated by FlutterFire CLI.
// This file should be version controlled.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcn8S4zCL7f7JqXqofDm-8Cmdy2W2DT-k',
    appId: '1:501406586454:web:57c8f5d3a44c3dd1398df7',
    messagingSenderId: '501406586454',
    projectId: 'sonxemay-cantho',
    authDomain: 'sonxemay-cantho.firebaseapp.com',
    databaseURL: 'https://sonxemay-cantho-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sonxemay-cantho.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0CG6EY9KALaZyfrBZrRyMUBRr2IvyKwc',
    appId: '1:501406586454:android:ce7b67194232c15a398df7',
    messagingSenderId: '501406586454',
    projectId: 'sonxemay-cantho',
    databaseURL: 'https://sonxemay-cantho-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sonxemay-cantho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCQIPHSbXCh7WTY3zZPm1_sRwPLDYvKdk',
    appId: '1:501406586454:ios:c01a752bdb3a1590398df7',
    messagingSenderId: '501406586454',
    projectId: 'sonxemay-cantho',
    databaseURL: 'https://sonxemay-cantho-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sonxemay-cantho.firebasestorage.app',
    androidClientId: '501406586454-hitlufrpg3ecb61184g56g2l7vbokarr.apps.googleusercontent.com',
    iosClientId: '501406586454-kpvioelue78v5tfekhtsbcb96onjbfe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotSonxemaycanthoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCQIPHSbXCh7WTY3zZPm1_sRwPLDYvKdk',
    appId: '1:501406586454:ios:c01a752bdb3a1590398df7',
    messagingSenderId: '501406586454',
    projectId: 'sonxemay-cantho',
    databaseURL: 'https://sonxemay-cantho-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sonxemay-cantho.firebasestorage.app',
    androidClientId: '501406586454-hitlufrpg3ecb61184g56g2l7vbokarr.apps.googleusercontent.com',
    iosClientId: '501406586454-kpvioelue78v5tfekhtsbcb96onjbfe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotSonxemaycanthoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcn8S4zCL7f7JqXqofDm-8Cmdy2W2DT-k',
    appId: '1:501406586454:web:eaf22ae6cff27b6b398df7',
    messagingSenderId: '501406586454',
    projectId: 'sonxemay-cantho',
    authDomain: 'sonxemay-cantho.firebaseapp.com',
    databaseURL: 'https://sonxemay-cantho-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sonxemay-cantho.firebasestorage.app',
  );

}